### ISSUE TITLE
installation: no module spherical kmeans

### ISSUE THREAD

**Issue by el2813** [clara-labs/spherecluster#2]
I'm using anaconda, installing in the environment where i have python3.4 version. 
I tried downloading via pip and via python setup.py install in this environment and also in a global, python2.7 environment, each time uninstalling everything and trying again. No luck. Everywhere I get a no-module "spherical_kmeans" message. What can be done here? Thanks a lot!

![1](https://cloud.githubusercontent.com/assets/20479431/17818014/7c9350ce-660f-11e6-916a-ad5bcafd8a39.JPG)
![2](https://cloud.githubusercontent.com/assets/20479431/17818015/7c94b252-660f-11e6-98ba-34b4e74e078e.JPG)
![3](https://cloud.githubusercontent.com/assets/20479431/17818013/7c929fee-660f-11e6-975a-d5953b52b837.JPG)

**Comment by jasonlaska** [comment]
Ah bummer!  I haven't tried it in anaconda, only pip (and with virtualenv).  One note is that it requires numpy/scipy to be installed ahead of time.  

It's possible that you might need to change this line: https://github.com/clara-labs/spherecluster/blob/develop/spherecluster/von_mises_fisher_mixture.py#L26

to be `from spherecluster import spherical_kmeans` instead (and then try running setup) and possible add `spherical_kmeans` to the `__init__.py` in the package.

Let me know if you figure out so I can patch it.

**Comment by jasonlaska** [comment]
@el2813 I've updated the package to use relative paths;  try installing `0.1.2` and see if that helps.  Cheers.

**Comment by el2813** [comment]
"try installing 0.1.2"
-ok!

**Comment by el2813** [comment]
yes!!!! it works! Soooo happy. Tnx! I saw awesome mit documentation about your spherical kmeans and von mises-fisher mixture, and I was like I have to try these!!! I gonna do word2vec and then feed that to one of your algorithms. For my current clustering with classical kmeans, preceded by sklearn tfidfvectorizer, I get mediocre results described with metrics below. So I'm super excited to try your package. have a nice day!


![metrics](https://cloud.githubusercontent.com/assets/20479431/17821851/c0855be4-6621-11e6-9593-25af9122b928.JPG)

**Comment by el2813** [comment]
By the way, your last name Laska in Ukrainian means "tenderness"/"gentleness"/"caressing"/"kindness." Very nice word. :)

**Comment by jasonlaska** [comment]
Good luck!  Results will vary depending how your data is distributed; just another tool try to (among several other clustering algs in sklearn).
