### ISSUE TITLE
SphericalKMeans does not converge

### ISSUE THREAD

**Issue by marcosterland** [clara-labs/spherecluster#3]
Hi, 
for some reason SphericalKMeans doesn't find any valid centroids. On my data. The same happens with randomly generated data, which clearly has clusters.

Running the following code always leads to the cluster centers `[1. 1. 1.]`:
```
from scipy.stats import vonmises
import numpy as np
from spherecluster import SphericalKMeans

ang = vonmises.rvs(25, loc=1, size=100)
ang = np.hstack((ang, vonmises.rvs(25, loc=3, size=100)))
ang = np.hstack((ang, vonmises.rvs(25, loc=5, size=100)))

skm = SphericalKMeans(n_clusters=3)
skm.fit(ang.reshape((-1, 1)))
print skm.cluster_centers_
```

Python 2.7.12,  spherecluster 0.1.2

Am I missing something?

**Comment by jasonlaska** [comment]
Hi @marcosterland,

In your example, `ang` is of shape `ang.shape = (300,)` so it is a single vector there is not much to cluster.  

The scipy.stats.vonmises routin only generates a univariate vMF distribution.  If you are trying to sample from a higher dimension mixture of vMF distribution, I recommend starting from this example: https://github.com/clara-labs/spherecluster/blob/develop/examples/small_mix_3d.py#L19-L36  and working with something like https://github.com/clara-labs/spherecluster/blob/develop/spherecluster/util.py .

cheers,
Jason

**Comment by jasonlaska** [comment]
Actually I guess it's 300 vectors of length 1. In this case, normalizing each length-1 vector will result in the value 1 for each vector, making the exercise uneventful (which is why you get 
```
[[ 1.]
 [ 1.]
 [ 1.]]
```
as output).

**Comment by marcosterland** [comment]
Thanks for your quick reply @jasonlaska .
It does make sense to cluster 1-D data. And in fact, the KMeans from scikit-learn finds the correct centers `[[1.] [3.] [5.]]` on the generated data.
But the scikit-learn KMeans uses standard Euclidean distance instead of the circular, so it's not applicable on e.g. angles.

**Comment by jasonlaska** [comment]
I refer you to https://en.wikipedia.org/wiki/Cosine_similarity,  the cosine between any two scalars is going to be 0 (as they all lie on the same axis) and therefore the cosine similarity (1- cos) will be 1.   I believe there might be a way to use the cosine distance in scikit-learn's k-means, you might want to give that a try.
