### ISSUE TITLE
Strict Matplotlib requirement prevents installation on python 3.6

### ISSUE THREAD

**Issue by ilektram** [clara-labs/spherecluster#4]
Hello,

Thanks for making this package, it is really useful!

I am using python 3.6 on OS X 10.12.6 and I tried to install the package through pip. The installation fails while trying to install the `matplotlob` version as specified in [requirements.txt](https://github.com/clara-labs/spherecluster/blob/3e20dec7b4e244a16107495360c514a8368d16a3/requirements.txt#L3) file. This is, I think, a known issue for `matplotlib` which was fixed in later versions (see issues like https://github.com/matplotlib/matplotlib/issues/3889). I have successfully installed `matplotlib` version `2.0.2` in my environment. 

I think that there are 3 ways of solving this issue.
1. Bump the version of `matplotlib` this package depends on
2. Remove the strict dependency (==) requirement
3. Remove the `matplotlib` dependency altogether. From what I understand, `matplotlib` is only used in the examples and is thus not needed for the packaged version of the library (similar to `seaborn` and `tabulate`)

**Comment by jasonlaska** [comment]
Thanks for the feedback.

I've cleaned things up a bit and the tests and examples now run in python3.  You can pull down the latest version (0.1.5) to get these updates or pull master.
