### ISSUE TITLE
How to use spherecluster in Jupyter notebook

### ISSUE THREAD

**Issue by dfafalis** [clara-labs/spherecluster#6]
Hi Jason,
I am trying to use the package 'spherecluster' in Jupyter notebook, but I encounter the following message:
ModuleNotFoundError: No module named 'spherecluster'
after the command "import spherecluster"
I have installed the package through the Windows command window without problem.
Could you give me an insight of what I have done wrong?
Thank you.
Dmitry

**Comment by jasonlaska** [comment]
Hi @dfafalis, I'm not super familiar with the windows setup but the error your seeing has to do with the package not being in your environment or python path which is a bit outside the scope of issues for this repo.  Perhaps consult https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation for pip installations in windows.

**Comment by dfafalis** [comment]
Thank you Jason.
I figured it out.
